Tp2Module05LesPizzas/Models/PizzaGestionVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BO;
using Tp2Module05LesPizzas.CheckForm;

namespace Tp2Module05LesPizzas.Models
{
    public class PizzaGestionVM
    {
        public Pizza Pizza { get; set; }

        [Required]
        [DisplayName("Pates")]
        public int IdPate { get; set; }
        public List<Pate> Pates { get; set; }

        [Required]
        [DisplayName("Ingrédients")]
        public List<int> IdIngredients { get; set; }
        public List<Ingredient> Ingredients { get; set; }

    }
}

Tp2Module05LesPizzas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tp2Module05LesPizzas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Tp2Module05LesPizzas/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BO;
using Tp2Module05LesPizzas.Models;
using Tp2Module05LesPizzas.Utils;
using System.ComponentModel.DataAnnotations;

namespace Tp2Module05LesPizzas.Controllers
{
    public class PizzaController : Controller
    {
        // GET: Pizza
        public ActionResult Index()
        {
            return View(FakeDbPizza.Instance.Pizzas);
        }

        // GET: Pizza/Details/id
        public ActionResult Details(int id)
        {
            Pizza pizza = FakeDbPizza.Instance.Pizzas.FirstOrDefault(p => p.Id == id);
            return View(pizza);
        }

        // GET: Pizza/Create
        public ActionResult Create()
        {
            PizzaGestionVM pizzaGestionVM = new PizzaGestionVM()
            { 
                Pizza = new Pizza(), 
                Ingredients = FakeDbPizza.Instance.IngredientsDisponibles, 
                Pates = FakeDbPizza.Instance.PatesDisponibles 
            };
            return View(pizzaGestionVM);
        }

        // POST: Pizza/Create
        [HttpPost]
        public ActionResult Create(PizzaGestionVM pizzaGestionVM)
        {
            try
            {
                if (ModelState.IsValid && IsNameUnique(pizzaGestionVM) && IsIngredientListUnique(pizzaGestionVM))
                {
                    Pizza pizza = new Pizza();
                    pizza.Id = FakeDbPizza.Instance.Pizzas.Count == 0 ? 1 : FakeDbPizza.Instance.Pizzas.Max(x => x.Id) + 1;
                    pizza.Nom = pizzaGestionVM.Pizza.Nom;
                    pizza.Pate = FakeDbPizza.Instance.PatesDisponibles.FirstOrDefault(p => p.Id == pizzaGestionVM.IdPate);
                    pizza.Ingredients = FakeDbPizza.Instance.IngredientsDisponibles.Where(i => pizzaGestionVM.IdIngredients.Contains(i.Id)).ToList();
                    FakeDbPizza.Instance.Pizzas.Add(pizza);
                    return RedirectToAction("Index");
                }
                pizzaGestionVM.Ingredients = FakeDbPizza.Instance.IngredientsDisponibles;
                pizzaGestionVM.Pates = FakeDbPizza.Instance.PatesDisponibles;
                return View(pizzaGestionVM);
            }
            catch
            {
                pizzaGestionVM.Ingredients = FakeDbPizza.Instance.IngredientsDisponibles;
                pizzaGestionVM.Pates = FakeDbPizza.Instance.PatesDisponibles;
                return View(pizzaGestionVM);
            }
        }

        // GET: Pizza/Edit/id
        public ActionResult Edit(int id)
        {
            Pizza pizza = FakeDbPizza.Instance.Pizzas.FirstOrDefault(p => p.Id == id);
            List<int> idIngredients = new List<int>();

            foreach (Ingredient ingredient in pizza.Ingredients)
            {
                idIngredients.Add(ingredient.Id);
            }

            PizzaGestionVM pizzaGestionVM = new PizzaGestionVM()
            {
                Pizza = pizza,
                IdPate = pizza.Pate.Id,
                IdIngredients = idIngredients,
                Ingredients = FakeDbPizza.Instance.IngredientsDisponibles,
                Pates = FakeDbPizza.Instance.PatesDisponibles
            };

            return View(pizzaGestionVM);
        }

        // POST: Pizza/Edit/id
        [HttpPost]
        public ActionResult Edit(int id, PizzaGestionVM pizzaGestionVM)
        {
            try
            {
                if (ModelState.IsValid && IsNameUnique(pizzaGestionVM) && IsIngredientListUnique(pizzaGestionVM))
                {
                    Pizza pizza = FakeDbPizza.Instance.Pizzas
                        .FirstOrDefault(p => p.Id == id);
                    
                    pizza.Nom = pizzaGestionVM.Pizza.Nom;
                    
                    pizza.Ingredients = FakeDbPizza.Instance.IngredientsDisponibles
                        .Where(i => pizzaGestionVM.IdIngredients
                        .Contains(i.Id))
                        .ToList();
                    
                    pizza.Pate = FakeDbPizza.Instance.PatesDisponibles
                        .FirstOrDefault(p => p.Id == pizzaGestionVM.IdPate);
                   
                    return RedirectToAction("Index");
                }
                pizzaGestionVM.Ingredients = FakeDbPizza.Instance.IngredientsDisponibles;
                pizzaGestionVM.Pates = FakeDbPizza.Instance.PatesDisponibles;
                return View(pizzaGestionVM);

            }
            catch
            {
                pizzaGestionVM.Ingredients = FakeDbPizza.Instance.IngredientsDisponibles;
                pizzaGestionVM.Pates = FakeDbPizza.Instance.PatesDisponibles;
                return View(pizzaGestionVM);
            }
        }

        // GET: Pizza/Delete/id
        public ActionResult Delete(int id)
        {
            PizzaGestionVM pizzaGestion = new PizzaGestionVM();
            pizzaGestion.Pizza = FakeDbPizza.Instance.Pizzas.FirstOrDefault(x => x.Id == id);
            return View(pizzaGestion);
        }

        // POST: Pizza/Delete/id
        [HttpPost]
        public ActionResult Delete(int id, Pizza pizza)
        {
            try
            {
                FakeDbPizza.Instance.Pizzas.Remove(FakeDbPizza.Instance.Pizzas.FirstOrDefault(p => p.Id == id));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        private bool ValidateVM(PizzaGestionVM pizzaGestionVM)
        {
            bool result = true;
            return result;
        }

        private bool IsNameUnique(PizzaGestionVM pizzaGestionVM)
        {
            bool result = !FakeDbPizza.Instance.Pizzas.Any(p => p.Nom == pizzaGestionVM.Pizza.Nom);
            if (!result)
                ModelState.AddModelError("Pizza.Nom", "Il existe déjà une pizza portant ce nom");
            return result;
        }

        private bool IsIngredientListUnique(PizzaGestionVM pizzaGestionVM)
        {
            bool result = true;

            foreach (var pizza in FakeDbPizza.Instance.Pizzas)
            {
                if (pizza.Ingredients.Select(i => i.Id).SequenceEqual(pizzaGestionVM.IdIngredients))
                {
                    result = false;
                    ModelState.AddModelError("IdIngredients", "Il existe déjà une pizza composée de ces ingrédients");
                    break;
                }
            }
            return result;
        }

    }
}

Tp2Module05LesPizzas/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tp2Module05LesPizzas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tp2Module05LesPizzas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Tp2Module05LesPizzas/Views/Pizza/Create.cshtml
@model Tp2Module05LesPizzas.Models.PizzaGestionVM

<h2>Création une Pizza</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pizza.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pizza.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pizza.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pates, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.IdPate, Model.Pates.Select(item => new SelectListItem { Text = item.Nom, Value = item.Id.ToString() }), "Sélectionner une pate")
            <br />
            @Html.ValidationMessageFor(model => model.IdPate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredients, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.ListBoxFor(model => model.IdIngredients, Model.Ingredients.Select(item => new SelectListItem { Text = item.Nom, Value = item.Id.ToString() }))
            <br />
            @Html.ValidationMessageFor(model => model.IdIngredients, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Valider" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index", new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tp2Module05LesPizzas/Views/Pizza/Delete.cshtml
@model Tp2Module05LesPizzas.Models.PizzaGestionVM

@{
    ViewBag.Title = "Supprimer une Pizza";
}

<h2>Supprimer la Pizza</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pizza.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pizza.Nom)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="@ViewBag.Title" class="btn btn-warning" /> |
        @Html.ActionLink("Retour", "Index", new { @class = "btn btn-default" })
    </div>
    }
</div>

Tp2Module05LesPizzas/Views/Pizza/Details.cshtml
@model BO.Pizza

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pizza</h4>
    <hr />

    @Html.Partial("_PizzaDetails", Model)

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" }) |
    @Html.ActionLink("Retour", "Index", new { @class = "btn btn-info" })
</p>

Tp2Module05LesPizzas/Views/Pizza/Edit.cshtml
@model Tp2Module05LesPizzas.Models.PizzaGestionVM

@{
    ViewBag.Title = "Editer une Pizza";
}

<h2>Edition de la Pizza</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pizza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pizza.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pizza.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pizza.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pates, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.IdPate, Model.Pates.Select(item => new SelectListItem { Text = item.Nom, Value = item.Id.ToString() }), "Sélectionner une pate")
            <br />
            @Html.ValidationMessageFor(model => model.IdPate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ingredients, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.ListBoxFor(model => model.IdIngredients, Model.Ingredients.Select(item => new SelectListItem { Text = item.Nom, Value = item.Id.ToString() }))
            <br />
            @Html.ValidationMessageFor(model => model.IdIngredients, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index", new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tp2Module05LesPizzas/Views/Pizza/Index.cshtml
@model IEnumerable<BO.Pizza>

@{
    ViewBag.Title = "Index";
}

<h2>Gestion des Pizzas</h2>

<p>
    @Html.ActionLink("Créer une Pizza", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingredients)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @if (item.Pate != null)
                {
                    @Html.DisplayFor(modelItem => item.Pate.Nom)
                }
            </td>
            <td>
                @if (item.Ingredients != null)
                {
                    foreach (var ingredient in item.Ingredients)
                    {
                        @Html.DisplayFor(i => ingredient.Nom) <br />
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Modifier", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                @Html.ActionLink("Détails", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                @Html.ActionLink("Supprimer", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

Tp2Module05LesPizzas/Views/Pizza/_PizzaDetails.cshtml
@model BO.Pizza

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Nom)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Nom)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Pate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Pate.Nom)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Ingredients)
    </dt>
    @foreach (var ingredient in Model.Ingredients)
    {
        <dd>
            @Html.DisplayFor(model => ingredient.Nom)
        </dd>
    }
</dl>

Tp2Module05LesPizzas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pizza Pie", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Gestion Pizza", "Index", "Pizza")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>